http-port: 23940 #clash流量代理端口，可以修改，注意端口占用
api-port: 23941 #api端口，可以修改，注意端口占用
threads: 50 #线程数，指一次扫描多少个节点，视系统配置情况而定，此处为50个线程
source: data/input.yaml #你的输入文件名，同级或下级目录的本地文件, 也可以是http(s)超文本传输协议的远程文件，注意必须是clash配置文件格式, 此处为下级目录data里的input.yaml
# source: https://ghproxy.com/https://raw.githubusercontent.com/anjue39/openit/main/utils/pool/output.yaml #你的输入文件名，同级、上级或下级目录的本地clash配置文件，上级目录的文件需要使用"../"进行引导, 也支持http(s)超文本传输协议的远程文件，注意必须是clash标准配置文件格式，此处为以ghproxy.com作为免翻墙的openit节点池
outfile: data/check.yaml #你的输出文件名, 同级或下级目录的本地文件，注意输出文件也是clash配置文件格式, 此处为下级目录data里的check.yaml
test-url: https://www.youtube.com/s/player/23010b46/player_ias.vflset/en_US/remote.js #本地延迟测试国外地址, 可以更改，注意必须是GFW完全屏蔽的网站，github.com不行，此处为YouTube的某个js文件
test-url1: http://anjue.oicp.net:85/remote.js #外国服务器延迟测试的本地地址，可选项。如果需要在外国服务器上测试本地路由的延迟，可以提供一个本地地址进行测试。本地测试不需要这个测试，注释掉
# test-url: https://cachefly.cachefly.net/10mb.test #本地延迟测试国外地址, 可以更改，注意必须是GFW完全屏蔽的网站，github.com不行，此处为YouTube的某个js文件
# test-url1: http://www.wuxikj.cn/serverlist.txt #外国服务器延迟测试本地路由地址, 可以更改
# test-url: https://gw.alicdn.com/bao/uploaded/LB1bC41LVXXXXcGXFXXXXXXXXXX.mp4 #延迟测试地址, 可以更改，注意必须是GFW完全屏蔽的网站，github.com不行，此处为YouTube的某个js文件
timeout: 1500 #测试的超时界限，单位: 毫秒
# 配置下载速度测试参数
download-test-enable: true                # 是否开启下载速度测试
download-test-url: 'https://cachefly.cachefly.net/1mb.test'   # 下载速度测试的URL
download-test-timeout: 10                 # 下载速度测试的超时时间，单位为秒
download-speed-threshold: 1               # 下载速度的阈值，大于该值才视为有效，单位为兆字节/秒（MB/s）
download_speed_threads: 5 #下载测试线程数，指一次扫描多少个节点，视系统配置情况而定，此处为5个线程，建议不超过5个，否则容易卡死
